name: CI/CD

on:
  push:
    branches: main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        run: |
          version=$(cat pyproject.toml | grep -oP '(?<=^version = ").*(?="$)')
          echo "APP_VERSION=${version}" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.APP_NAME }}:${{ env.APP_VERSION }}

      - name: Checkout Helm chart repository
        uses: actions/checkout@v4
        with:
          repository: mashkovd/argocdApps
          token: ${{ secrets.HELM_REPO_TOKEN }}

      - name: Update Helm chart values
        run: |
          cd helm-exchange-bot
          echo "APP_VERSION=${{ env.APP_VERSION }}"
          sed -i 's/^appVersion:.*/appVersion: "${{ env.APP_VERSION }}"/' Chart.yaml

      - name: Commit and push Helm chart changes
        run: |
          git config --global user.email "mashkovd@live.ru"
          git config --global user.name "Dmitrii.Mashkov"
          git add .
          git commit -m "Update Helm chart values. Version: ${{ env.APP_VERSION }}"
          git push
