name: ci

on:
  push:
    branches: main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: extract-version
        run: |
          version=$(cat pyproject.toml | grep -oP '(?<=^version = ").*(?="$)')
          echo "::set-output name=version::$version"
          echo $version > version.txt
          echo "APP_VERSION=${version}" >> $GITHUB_ENV
          echo $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.APP_NAME }}:${{ steps.extract-version.outputs.version }}

      - name: Checkout Helm chart repository
        uses: actions/checkout@v4
        with:
          repository: mashkovd/argocdApps
          token: ${{ secrets.HELM_REPO_TOKEN }}
      - name: Update values.yaml
        run: |
          cd helm-exchange-bot
          echo ${{ env.APP_VERSION }}
          sed -i 's/^appVersion:.*/appVersion: "${{ env.APP_VERSION }}"/' Chart.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "mashkovd@live.ru"
          git config --global user.name "Dmitrii.Mashkov"
          git add .
          git commit -m "Update Helm chart values"
          git push