name: ci

on:
  push:
    branches: main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: extract-version
        run: |
          version=$(cat pyproject.toml | grep -oP '(?<=^version = ").*(?="$)')
          echo "::set-output name=version::$version"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.APP_NAME }}:${{ steps.extract-version.outputs.version }}
